apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: {{ .Values.mysqlservice.service.port }}
      targetPort: {{ .Values.mysqlservice.service.targetPort }}
  clusterIP: {{ .Values.mysqlservice.service.clusterIP }}
