apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  labels:
    app: usermgmt-webapp
spec:
  type: {{ .Values.userwebappservice.type }}
  selector:
    app: usermgmt-webapp
  ports:
    - port: {{ .Values.userwebappservice.port }}
      targetPort: {{ .Values.userwebappservice.targetport }}
